=== JuamBer/1DAM-LenguajeDeMarcas/023. LibroDTD/libro.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro (isbn, titulo, nivel, autores, editorial, fecha_publicacion, webs, precio)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>
<!ATTLIST nivel
          tratamiento CDATA #REQUIRED>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT fecha_publicacion (#PCDATA)>
<!ELEMENT webs (web+)>
<!ELEMENT web (#PCDATA)>
<!ATTLIST web
          ruta CDATA #REQUIRED>
<!ELEMENT precio (#PCDATA)>

=== JuamBer/1DAM-LenguajeDeMarcas/020. LibroXML/libro.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE libros SYSTEM "libro.dtd">
<libros>
    <libro>
        <isbn>0-7645-2641-3</isbn>
        <titulo>Titulo</titulo>
        <nivel tratamiento="básico"/>
        <autores>
            <autor>Autor</autor>
            <autor>Autor</autor>
        </autores>
        <editorial>Editorial</editorial>
        <fecha_publicacion>10/02/2021</fecha_publicacion>
        <webs>
            <web ruta="rutaAmazon">Web Amazon</web>
            <web ruta="rutaLaCasaDelLibro">Web LaCasaDelLibro</web>
        </webs>
        <precio>Precio</precio>
    </libro>
    <libro>
        <isbn>0-7645-2641-3</isbn>
        <titulo>Titulo</titulo>
        <nivel tratamiento="básico"/>
        <autores>
            <autor>Autor</autor>
        </autores>
        <editorial>Editorial</editorial>
        <fecha_publicacion>10/02/2021</fecha_publicacion>
        <webs>
            <web ruta="rutaLaCasaDelLibro">Web LaCasaDelLibro</web>
        </webs>
        <precio>Precio</precio>
    </libro>
    <libro>
        <isbn>0-7645-2641-3</isbn>
        <titulo>Titulo</titulo>
        <nivel tratamiento="básico"/>
        <autores>
            <autor>Autor</autor>
            <autor>Autor</autor>
        </autores>
        <editorial>Editorial</editorial>
        <fecha_publicacion>10/02/2021</fecha_publicacion>
        <webs>
            <web ruta="rutaAmazon">Web Amazon</web>
            <web ruta="rutaLaCasaDelLibro">Web LaCasaDelLibro</web>
        </webs>
        <precio>Precio</precio>
    </libro>
    <libro>
        <isbn>0-7645-2641-3</isbn>
        <titulo>Titulo</titulo>
        <nivel tratamiento="básico"/>
        <autores>
            <autor>Autor</autor>
            <autor>Autor</autor>
        </autores>
        <editorial>Editorial</editorial>
        <fecha_publicacion>10/02/2021</fecha_publicacion>
        <webs>
            <web ruta="rutaAmazon">Web Amazon</web>
            <web ruta="rutaLaCasaDelLibro">Web LaCasaDelLibro</web>
        </webs>
        <precio>Precio</precio>
    </libro>
    <libro>
        <isbn>0-7645-2641-3</isbn>
        <titulo>Titulo</titulo>
        <nivel tratamiento="básico"/>
        <autores>
            <autor>Autor</autor>
        </autores>
        <editorial>Editorial</editorial>
        <fecha_publicacion>10/02/2021</fecha_publicacion>
        <webs>
            <web ruta="rutaAmazon">Web Amazon</web>
        </webs>
        <precio>Precio</precio>
    </libro>
</libros>
