=== JuamBer/1DAM-LenguajeDeMarcas/028.Reyes/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="reyesEspañoles">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="rey" type="tipor" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="reina" type="tipor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="tipor">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/> 
      <xs:element name="padre" type="xs:string"/> 
      <xs:element name="madre" type="xs:string"/> 
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== JuamBer/1DAM-LenguajeDeMarcas/028. Reyes/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<reyesEspañoles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/DAM6J_GB/Documents/Lenguaje%20De%20Marcas/028.%20Reyes/index.xsd">
  <rey>
    <nombre>Felipe III</nombre>
    <padre>Felipe II</padre>
    <madre>Ana de Austria</madre>
  </rey>
  <reina>
    <nombre>Juana la Loca</nombre>
    <padre>Fernando el Católico</padre>
    <madre>Isabel la Católica</madre>
  </reina>
  <rey>
    <nombre>Carlos I</nombre>
    <padre>Felipe el Hermoso</padre>
    <madre>Juan la Loca</madre>
  </rey>
</reyesEspañoles>
